# Generated by Django 6.0.5 on 2026-05-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='available_vaccines',
            field=models.ManyToManyField(related_name='clinics', to='vaccination.vaccine'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
        ),
    ]
