# Generated by Django 6.0.5 on 2026-05-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Forgot', 'Forgot'), ('Sick', 'Sick'), ('Travel', 'Travel'), ('No Slot', 'No Slot')], max_length=50)),
                ('suggested_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vaccination_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plans', to='vaccination.vaccinationschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ForgotRecoveryPlan',
            fields=[
                ('recoveryplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recovery.recoveryplan')),
                ('reminder_frequency', models.CharField(max_length=100)),
            ],
            bases=('recovery.recoveryplan',),
        ),
        migrations.CreateModel(
            name='NoSlotRecovery',
            fields=[
                ('recoveryplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recovery.recoveryplan')),
                ('alternative_clinic', models.CharField(max_length=100)),
            ],
            bases=('recovery.recoveryplan',),
        ),
        migrations.CreateModel(
            name='SickRecovery',
            fields=[
                ('recoveryplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recovery.recoveryplan')),
                ('delay_days', models.IntegerField()),
            ],
            bases=('recovery.recoveryplan',),
        ),
        migrations.CreateModel(
            name='TravelRecovery',
            fields=[
                ('recoveryplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recovery.recoveryplan')),
                ('clinic_name', models.CharField(max_length=100)),
            ],
            bases=('recovery.recoveryplan',),
        ),
    ]
